// Контент-паки серий. Дефолт (huang/NVDA) живёт в engine.js; здесь — Сейлор/MSTR и Виталик/ETH.
// Band'ы = 52w на 2026-06-10, ПРОВИЗОРНЫЕ до заморозки на дату старта коллекции.
// Факты: MSTR 52w 104.17–457.20 (цена ~120.44); Strategy держит 845,256 BTC по средней $75,681.
// ETH 52w 1,388.12–4,955.90 (цена ~1,670). Обе серии сейчас в выгорании — у NVDA зеркальная фаза.
window.SERIES_CFG={
saylor:{
 name:'Michael Saylor',ticker:'MSTR',low:104.17,high:457.20,ath:'457.20',copy:'21,000,000 ONLY',
 bubbleRow:['LEVERAGED BITCOIN','20__','2026'],
 heads:{
  hot:['STRATEGY BUYS THE DIP, AGAIN','THERE IS NO SECOND BEST','THE INFINITE MONEY GLITCH',
   'ANOTHER BILLION, ANOTHER BLOCK','WALL ST. FUNDS THE ORANGE STANDARD','MSTR PREMIUM WIDENS',
   'SELL BONDS, BUY BITCOIN','LEVERAGE AS A RELIGION','845,256 AND COUNTING','YOU DO NOT SELL YOUR BITCOIN',
   'THE TREASURY THAT ATE A COMPANY','CONVERTS OVERSUBSCRIBED, AGAIN'],
  mid:['IS MSTR A FUND OR A FAITH?','WHAT IF THE PREMIUM CLOSES?','A SOFTWARE COMPANY, TECHNICALLY',
   'HOW MUCH LEVERAGE IS TOO MUCH?','CONVERTIBLE NOTES ALL THE WAY DOWN','NAV IS A SOCIAL CONSTRUCT',
   '21 MILLION DIVIDED BY EVERYONE','THE $64 BILLION AVERAGE','ONE MAN, ONE BALANCE SHEET',
   'WHO BUYS THE LAST CONVERT?'],
  cold:['MARGIN CALL AT THE CHURCH OF BITCOIN','THE PREMIUM IS GONE','FORCED SELLER',
   'CONVERTS COME DUE','THE GREAT UNWIND, LEVERED','SOFTWARE COMPANY SEEKS SOFTWARE REVENUE',
   'HODL MEETS HAIRCUT','DILUTION AT THE BOTTOM','WHO LIQUIDATES THE LIQUIDATOR?',
   'NAV BELOW ONE','THE ORANGE STANDARD, REPRICED']},
 ticks:{
  hot:['MSTR 457.20 ▲ +9.8% · MNAV 2.4×','BTC HELD 845,256 · AVG $75,681','BTC 118,400 ▲ · MSTR BETA 3.1',
   'CONVERTS $7.3B · COUPON 0.625%','ATM ISSUANCE $2.1B THIS WEEK · ACCRETIVE','OPT FLOW ▲ CALLS 78% · IV 96'],
  mid:['NASDAQ: MSTR · 52W 104.17–457.20','BTC HELD 845,256 · COST BASIS $63.9B','MNAV 1.1× · PREMIUM THINNING',
   'SOFTWARE REV $115M · TREASURY $64B','SHORT INT 11% · DAYS TO COVER 2.4','VOL 28,441,090 · BETA 3.1'],
  cold:['MSTR 120.44 ▼ −57% YOY','MNAV 0.9× · DISCOUNT TO COIN','BTC 74,300 ▼ · AVG COST UNDERWATER',
   'CONVERT WALL 2028 · REFI RISK ▲','FORCED LIQUIDATION WATCH · LULD 09:47','OPT FLOW ▼ PUTS 81% · IV 140']},
 stamps:{
  hot:['₿','845,256','2.4×','+9.8%','457.20','21M','∞'],
  mid:['1.0×','104.17','52W','75,681','?'],
  cold:['0.9×','▼','120.44','−57%','MARGIN','SOLD?']},
 quotes:{
  hot:['“there is no second best”','“bitcoin is hope”','“we will never sell”','“volatility is vitality”',
   '“the dollar is melting ice”'],
  mid:['“a company is just a wrapper”','“the premium is the product”','“laser eyes fade, debt does not”'],
  cold:['“we remain committed to the strategy”','“temporary impairment”','“the thesis is unchanged”',
   '“no margin calls expected” — filing, p.84']},
 pageidx:{
  hot:'MARKETS B1 · CRYPTO C1 · OPINION A19 · YACHTS D4',
  mid:'MARKETS B1 · CRYPTO C1 · OPINION A19 · OBITUARIES D7',
  cold:'MARKETS B1 · LIQUIDATIONS C1 · RESTRUCTURING D2 · OBITUARIES D7'},
 corpus:{
  hot:'Every share sold buys more bitcoin and every bitcoin bought lifts the share. The flywheel hums like a prayer '
   +'wheel and Wall Street queues to lend at zero for a glimpse of orange. The treasury grew past the company years '
   +'ago; now the company is a rumor attached to a balance sheet. Dilution is accretion, the deck says, and the deck '
   +'has been right the whole way up. There is no second best.',
  mid:'Somewhere inside the structure there is still a software business, small and warm, like a pilot light. Around '
   +'it: convertible notes, preferred stacks, at-the-market offerings, a premium that exists because people agree it '
   +'does. The man speaks in centuries and the market listens in quarters. Whether this is treasury management or '
   +'performance art depends on the closing price.',
  cold:'The premium went first, quietly, like air from a door left open. Then the converts grew teeth and the lawyers '
   +'started reading the indentures aloud. An average cost is a confession when the spot trades below it. The chair '
   +'still tweets sunrise photos; the desk sells what it swore it never would. Leverage is a religion until the '
   +'first margin call, after which it is a court filing.'},
 sect:[['COIN',310],['HOOD',98],['RIOT',11],['MARA',17],['CLSK',9],['SMLR',38],['BITO',22]],
 earn:[['BTC HELD',845256,0,''],['AVG COST',75681,0,''],['COST BASIS',63.9,0.2,'B'],
       ['MNAV',0.9,0.6,'×'],['CONVERTS',7.3,1,'B'],['SOFTWARE REV',0.11,0.02,'B']],
 glitch:{words:['₿','MSTR','BTC','21M','845,256','NAV','×3','HODL','SELL?','120.44','457.20','MARGIN'],
  heads:['THERE IS NO SECOND BEST','THE PREMIUM IS GONE','MARGIN CALL AT THE CHURCH OF BITCOIN',
   'STRATEGY BUYS THE DIP, AGAIN','NAV IS A SOCIAL CONSTRUCT','FORCED SELLER','YOU DO NOT SELL YOUR BITCOIN',
   'CONVERTS COME DUE'],
  ticks:['MSTR 120.44 ▼ −57% YOY','BTC HELD 845,256 · AVG $75,681','MNAV 0.9× · DISCOUNT TO COIN',
   '52W 104.17–457.20','CONVERTS $7.3B · COUPON 0.625%','OPT FLOW ▼ PUTS 81% · IV 140']}},
powell:{
 name:'Jerome Powell',ticker:'FED',low:6.55,high:8.97,ath:'8.97T',copy:'LEGAL TENDER',
 bubbleRow:['THE EVERYTHING BUBBLE','20__','2022'],
 heads:{
  hot:['THE PRINTER HUMS','WHATEVER IT TAKES, AGAIN','QE TO INFINITY','MONEY IS FREE. EVERYTHING IS A BUY',
   'THE FED PUT LIVES','LIQUIDITY FOR ALL','ZERO FOR LONGER','THE BALANCE SHEET DOUBLES',
   'ASSET PRICES ARE THE ECONOMY','BUY EVERYTHING, THE FED HAS YOUR BACK'],
  mid:['TRANSITORY','DATA DEPENDENT','SOFT LANDING, MAYBE','THE DOT PLOT SHRUGS','HIGHER FOR LONGER',
   'TWO MORE MEETINGS','WHAT IS NEUTRAL, ANYWAY?','THE LAST HIKE? THE FIRST CUT?',
   'PRICE STABILITY, EVENTUALLY','EIGHT MEETINGS A YEAR'],
  cold:['THE PRINTER COOLS','QT GRINDS ON','THE PUNCHBOWL IS GONE','LIQUIDITY LEAVES QUIETLY',
   'RESERVES RUN THIN','THE FED PUT IS DEAD','NO ONE BIDS THE LONG END','BALANCE SHEET ON A DIET',
   'HAWKS ALL THE WAY DOWN','AMPLE, FOR NOW']},
 ticks:{
  hot:['B/S $8.97T ▲ +112% SINCE 2020','FFR 0.00–0.25 · REAL YIELDS NEGATIVE','QE $120B/MO · RRP $0',
   '10Y 0.62% · VIX 12 · EVERYTHING ▲','REPO CALM · SPREADS CRUSHED'],
  mid:['FED · B/S BAND 6.55–8.97T (FROZEN)','FFR 3.75% · DOTS SCATTER','H.4.1 · WEDNESDAYS 16:30 ET',
   'CPI 2.6% · CORE 2.9% · PCE 2.4%','FOMC ×8/YR · MINUTES +3W'],
  cold:['B/S $6.71T ▼ · QT CONTINUES','LIQUIDITY −$2.3T OFF PEAK','RRP $6B · RESERVES "AMPLE?"',
   '10Y 4.21% · TERM PREMIUM RETURNS','TGA REFILL DRAINS $300B','BANK TERM FUNDING: CLOSED']},
 stamps:{
  hot:['$9T','0.00%','∞','+112%'],
  mid:['6.71T','3.75%','DOTS','?','×8'],
  cold:['QT','▼','−$2.3T','AMPLE?']},
 quotes:{
  hot:['“not even thinking about thinking about raising rates”','“inflation is transitory”',
   '“we have the tools”','“whatever it takes”'],
  mid:['“data dependent”','“policy is in a good place”','“neutral is a concept, not a number”'],
  cold:['“some pain ahead”','“higher for longer”','“the disinflationary process has begun” — again',
   '“no one rings a bell at the bottom of liquidity”']},
 pageidx:{
  hot:'MARKETS B1 · RATES C1 · OPINION A19 · MANSIONS D4',
  mid:'MARKETS B1 · RATES C1 · OPINION A19 · OBITUARIES D7',
  cold:'MARKETS B1 · RATES C1 · BANK FAILURES D2 · OBITUARIES D7'},
 corpus:{
  hot:'The printer hums in the basement of everything. Money costs nothing and therefore everything costs anything; '
   +'cap rates compress, junk yields vanish, a jpeg clears at the price of a house. The committee buys bonds the way '
   +'weather happens — vast, impersonal, weekly. Skeptics talk about consequences; the tape talks louder. Liquidity '
   +'is a tide that believes itself to be a sea.',
  mid:'Eight meetings a year, a scatter of dots, a podium and a thousand readings of the word patient. Policy works '
   +'with long and variable lags, which is to say nobody knows; the chair says data dependent and the market hears '
   +'whatever it brought into the room. Somewhere between transitory and entrenched, between soft landing and the '
   +'other kind, the balance sheet breathes.',
  cold:'Liquidity leaves the way it came, only quieter. Every Wednesday at four-thirty the sheet is a little thinner, '
   +'a few billion of belief allowed to mature and die unreplaced. Reserves are ample until the morning a repo desk '
   +'says otherwise. The punchbowl is gone and the party guests are checking coat-room tickets for collateral. The '
   +'printer is not off. It is listening.'},
 sect:[['10Y',4.2],['2Y',3.8],['DXY',103],['SPX',6800],['GOLD',3300],['OIL',71]],
 earn:[['B/S',6.71,0.05,'T'],['TSY',4.47,0.05,'T'],['MBS',1.97,0.02,'T'],
       ['FFR',3.75,0.25,'%'],['RRP',6,4,'B'],['TGA',876,40,'B']]},
vitalik:{
 name:'Vitalik Buterin',ticker:'ETH',low:1388.12,high:4955.90,ath:'4,955.90',copy:'GAS 12 GWEI',
 bubbleRow:['THE WORLD COMPUTER','20__','2026'],
 logo:{kind:'eth'},logoBias:0.85,                            // ETH-серия — много диамантов/графики
 heads:{
  hot:['ETHEREUM EATS WALL STREET','ULTRASOUND MONEY','THE WORLD COMPUTER BOOTS','BLACKROCK STAKES',
   'GAS AT 200 GWEI AND NOBODY CARES','STAKING YIELD BEATS BONDS','THE FLIPPENING WATCH','REAL ESTATE, ON-CHAIN',
   'L2s ALL THE WAY UP','EVERY BANK RUNS A VALIDATOR','TOKENIZE EVERYTHING','THE MERGE WAS JUST THE START',
   'ETH IS THE BASE LAYER OF MONEY','DEFI SUMMER, FOREVER','THE TRIPLE HALVING','THE END OF THE DOLLAR',
   'NFTs ARE BACK, OBVIOUSLY','SOVEREIGN ROLLUPS','RESTAKE EVERYTHING','THE ETHEREALIZATION OF VALUE'],
  mid:['WHAT IS ETH, LEGALLY?','PROTOCOL OR CASINO?','SCALING SOON™','THE ROADMAP CURVES AGAIN',
   'VITALIK SELLS? VITALIK SELLS.','DECENTRALIZED ENOUGH?','IS THE MERGE PRICED IN, STILL?',
   'WHO PAYS FOR BLOCKSPACE?','A COMPUTER IN SEARCH OF A PROBLEM','SECURITY OR COMMODITY?',
   'THE DANKSHARDING DECADE','SUFFICIENTLY DECENTRALIZED?','GAS FEES, EXPLAINED AGAIN','TOO MANY L2s?'],
  cold:['GAS 2 GWEI: NOBODY LEFT','TVL EVAPORATES','THE FLIPPENING, INVERTED','STAKERS UNSTAKE',
   'L2s GO DARK','WORLD COMPUTER, SLEEP MODE','DEFI WINTER IS HERE','SUPPLY ULTRASOUND, DEMAND UNSOUND',
   'THE CHAIN IS FINE. THE PRICE IS NOT.','EXIT LIQUIDITY, FINALIZED','THE MEMPOOL IS A GRAVEYARD',
   'VALIDATORS EXIT THE QUEUE','RESTAKING UNWINDS','THE WORLD COMPUTER IDLES','BLOCKSPACE, FOR FREE NOW']},
 ticks:{
  hot:['ETH 4,955 ▲ +6.2% · GAS 142 GWEI','STAKED 34.2M ETH · YIELD 5.1%','TVL $184B ▲ · L2 TPS 4,800',
   'BURN > ISSUANCE · SUPPLY ▼','ETH/BTC 0.081 ▲ · FLIPPENING 61%','OPT FLOW ▲ CALLS 74% · IV 88'],
  mid:['ETH · 52W 1,388.12–4,955.90','STAKED 34.2M · VALIDATORS 1.07M','GAS 14 GWEI · BLOBS 6/BLOCK',
   'TVL $94B · DEX 7D $41B','ETH/BTC 0.034 · FLIPPENING 29%','FUNDING 0.00% · OI FLAT'],
  cold:['ETH 1,670 ▼ −41% YOY','GAS 3 GWEI · MEMPOOL EMPTY','TVL $48B ▼ · OUTFLOWS 9 WEEKS',
   'UNSTAKE QUEUE 18 DAYS','ETH/BTC 0.022 ▼ · LOWEST SINCE 2020','OPT FLOW ▼ PUTS 79% · IV 120']},
 stamps:{
  hot:['Ξ','4,955','5.1%','+62%','GWEI','∞/∞'],
  mid:['Ξ','1,388','52W','0.034','?'],
  cold:['Ξ','1,670','−41%','▼','2 GWEI','UNSTAKE']},
 quotes:{
  hot:['“ultrasound money”','“the world computer”','“yield is the new hodl”','“code is law, again”'],
  mid:['“the roadmap remains intact”','“decentralization is a spectrum”','“l2s are ethereum”'],
  cold:['“the chain worked exactly as designed”','“i sold at the top” — nobody','“funds are safu”',
   '“price is the last metric that matters” — holder of last metrics']},
 pageidx:{
  hot:'MARKETS B1 · PROTOCOLS C1 · OPINION A19 · DIGITAL ART D4',
  mid:'MARKETS B1 · PROTOCOLS C1 · OPINION A19 · OBITUARIES D7',
  cold:'MARKETS B1 · LIQUIDATIONS C1 · ABANDONED CHAINS D2 · OBITUARIES D7'},
 corpus:{
  hot:'Blockspace is the scarcest real estate on earth and every block is an auction for the future. Banks that '
   +'laughed now run validators in the same towers where they shorted it. The burn outruns issuance and the supply '
   +'curve bends like spacetime. Somewhere a teenager stakes a house deposit and the yield arrives every twelve '
   +'seconds, trustless, relentless, sincere.',
  mid:'The protocol ships, the price shrugs. Roadmaps fold into roadmaps: rollups, blobs, danksharding, names that '
   +'sound like weather systems. The founder gives away half his net worth and reads philosophy on planes. Whether '
   +'this is the financial system being rebuilt or a very elaborate seminar depends on who you ask and when.',
  cold:'Gas at two gwei is not efficiency, it is silence. The validators hum to an empty mempool like streetlights '
   +'over an evacuated city. TVL leaves in lots of eight figures; the bridges echo. The chain finalizes perfectly, '
   +'block after block of almost nothing, a world computer running screensavers. The technology was never the '
   +'question. The question was always the bid.'},
 sect:[['BTC',74300],['SOL',88],['BNB',520],['ARB',0.4],['OP',0.8],['LDO',1.1],['UNI',6.2]],
 earn:[['GAS',14,18,' GWEI'],['STAKED',34.1,0.4,'M ETH'],['TVL',48,12,'B'],
       ['BURNED',4.6,0.2,'M ETH'],['VALIDATORS',1.07,0.05,'M'],['L2 TPS',310,300,'']],
 glitch:{words:['Ξ','ETH','GWEI','TVL','MERGE','L2','1,670','4,955','STAKE','GAS','0.022'],
  heads:['ULTRASOUND MONEY','GAS 2 GWEI: NOBODY LEFT','THE FLIPPENING, INVERTED','WORLD COMPUTER, SLEEP MODE',
   'PROTOCOL OR CASINO?','VITALIK SELLS? VITALIK SELLS.','TVL EVAPORATES','SCALING SOON™'],
  ticks:['ETH 1,670 ▼ −41% YOY','GAS 3 GWEI · MEMPOOL EMPTY','STAKED 34.2M · VALIDATORS 1.07M',
   '52W 1,388.12–4,955.90','ETH/BTC 0.022 ▼','UNSTAKE QUEUE 18 DAYS']}},
gates:{
 name:'Bill Gates',ticker:'MSFT',low:356.28,high:555.45,ath:'555.45',copy:'640K OUGHT TO BE ENOUGH',
 bubbleRow:['THE SOFTWARE EMPIRE','20__','2000'],
 heads:{
  hot:['MICROSOFT EATS THE CLOUD','A PC ON EVERY DESK','THE AI COPILOT ERA','WINDOWS EVERYWHERE',
   'EMBRACE, EXTEND, EXTINGUISH','THE TRILLION-DOLLAR OS','AZURE TO INFINITY','SOFTWARE IS EATING SOFTWARE',
   'THE RICHEST MAN ON EARTH, AGAIN','EVERY ENTERPRISE RUNS WINDOWS'],
  mid:['IS THE MONOPOLY BACK?','ANTITRUST, AGAIN?','WHAT IS A COMPUTER FOR?','THE CLOUD OR THE COURTROOM?',
   'GATES GIVES IT AWAY','IS AI THE NEW WINDOWS?','THE LAST GREAT MONOPOLY','HOW MUCH IS TOO BIG?',
   'PLATFORM OR PRISON?','640K, REVISITED'],
  cold:['THE EMPIRE COOLS','DOT-COM, AGAIN?','THE LOST DECADE RETURNS','AZURE GROWTH STALLS',
   'BREAK IT UP','THE OS OF A SLOWER WORLD','COPILOT, GROUNDED','LEGACY IS A LIABILITY',
   'THE MONOPOLY THAT FORGOT TO INNOVATE','WHERE DID THE GROWTH GO?']},
 ticks:{
  hot:['MSFT 555.45 ▲ ATH · MKT CAP $4.1T','AZURE +31% YOY · COPILOT SEATS 90M','CLOUD GROSS MARGIN 71%',
   'P/E 38 · FWD P/E 32 · DIV 0.7%','AI CAPEX $80B/YR · GPUs ▲','OFFICE 400M SEATS · WINDOWS 1.4B'],
  mid:['NASDAQ: MSFT · 52W 356.28–555.45','MSFT 410.00 ▼ −14% YOY','AZURE +18% · DECELERATING',
   'P/E 31 · BUYBACK $60B','EPS 12.40 · FCF $74B','ENTERPRISE SEATS FLAT'],
  cold:['MSFT 356.28 ▼ −36% OFF HIGH','AZURE +6% · CLOUD WINTER','CAPEX WRITEDOWNS · AI OVERBUILT',
   'P/E 19 · MULTIPLE COMPRESSES','LAYOFFS 14,000 · REORG','GROWTH STOCK NO MORE']},
 stamps:{
  hot:['$4T','ATH','+31%','640K','×100'],
  mid:['356','P/E 31','52W','?','410'],
  cold:['−36%','▼','BREAK','356.28','SLOW']},
 quotes:{
  hot:['“a computer on every desk and in every home”','“we always overestimate the change in two years”',
   '“software is a great combination of artistry and engineering”','“your most unhappy customers are your greatest source of learning”'],
  mid:['“640K ought to be enough for anybody”','“i choose a lazy person to do a hard job”',
   '“success is a lousy teacher”','“the internet is becoming the town square”'],
  cold:['“we always underestimate the change in ten years”','“this is a temporary setback”',
   '“legacy is a dangerous word”','“the monopoly was the easy part”']},
 pageidx:{
  hot:'MARKETS B1 · TECH C3 · OPINION A19 · PHILANTHROPY D4',
  mid:'MARKETS B1 · TECH C3 · ANTITRUST C9 · OBITUARIES D7',
  cold:'MARKETS B1 · LAYOFFS C1 · ANTITRUST C9 · OBITUARIES D7'},
 corpus:{
  hot:'It started in a garage and ended up in every pocket, every desk, every server farm on earth. The empire '
   +'embraces, extends, and quietly extinguishes; the courtroom comes and goes and the licensing revenue never '
   +'stops. Now the same company that sold you an operating system sells you a copilot, and the cloud bills arrive '
   +'monthly, eternal, accretive. Skeptics called the top for thirty years and the cash kept compounding.',
  mid:'Somewhere between the antitrust trial and the foundation there is still a software business, vast and warm, '
   +'humming under fluorescent lights. The founder gives away his fortune and reads about malaria on planes. Whether '
   +'this is the most durable monopoly ever built or a legacy waiting to be disrupted depends on which quarter you '
   +'read and how you feel about the cloud.',
  cold:'Every empire has its lost decade, and the market is reading the old script again. Azure grows in single '
   +'digits, the capex writedowns arrive, and a growth stock quietly becomes a value trap. The same analysts who '
   +'modeled seats now model break-ups. The software still runs the world; the multiple no longer believes it.'},
 sect:[['AAPL',210],['GOOG',180],['AMZN',190],['NVDA',120],['ORCL',140],['CRM',230]],
 earn:[['REV',62,5,'B'],['CLOUD',28,3,'B'],['OP INC',27,3,'B'],['EPS',12.4,1,''],['BUYBACK',60,5,'B'],['CAPEX',80,10,'B']]},
zuck:{
 name:'Mark Zuckerberg',ticker:'META',low:520.26,high:796.25,ath:'796.25',copy:'MOVE FAST',
 bubbleRow:['THE METAVERSE','20__','2022'],
 heads:{
  hot:['META EATS THE FUTURE','THE METAVERSE IS HERE','SUPERINTELLIGENCE, SOON','LEGS, FINALLY',
   'AI GLASSES FOR EVERYONE','THE YEAR OF EFFICIENCY PAYS OFF','5 BILLION USERS AND COUNTING','OPEN SOURCE WINS',
   'ADS ARE INFINITE','MOVE FAST AND PRINT MONEY'],
  mid:['IS THE METAVERSE REAL?','HOW MANY BILLIONS ON LEGS?','PIVOT NUMBER FOUR','THE PRIVACY QUESTION, AGAIN',
   'AVATAR OR APPARITION?','WHO ASKED FOR THIS?','REALITY LABS: HOW LONG?','A SOCIAL NETWORK, STILL?',
   'THE TOLL ON ATTENTION','OPEN OR JUST FREE?'],
  cold:['REALITY LABS LOSES ANOTHER BILLION','THE METAVERSE IS EMPTY','PIVOT, AGAIN','THE LEGS WERE A LIE',
   'AI CAPEX, UNANSWERED','EFFICIENCY MEETS GRAVITY','NOBODY LOGS ON','THE TOLL IS DUE',
   'A GHOST TOWN IN 3D','WHERE DID THE USERS GO?']},
 ticks:{
  hot:['META 796.25 ▲ ATH · MKT CAP $2.0T','DAU 3.4B ▲ · ARPU $14.20','AI CAPEX $65B/YR · GPUs 600K',
   'P/E 29 · OP MARGIN 42%','REALITY LABS −$4.5B/Q · "INVESTING"','REELS ▲ · ENGAGEMENT ▲'],
  mid:['NASDAQ: META · 52W 520.26–796.25','META 568.00 ▼ −12% OFF HIGH','DAU 3.3B · ARPU FLAT',
   'P/E 24 · BUYBACK $50B','EPS 23.10 · FCF $52B','RL BURN $40B CUMULATIVE'],
  cold:['META 520.26 ▼ −35% OFF HIGH','RL LOSSES $20B/YR · NO PRODUCT','AD PRICES ▼ · ENGAGEMENT ▼',
   'P/E 13 · MULTIPLE HALVES','LAYOFFS 21,000 · "FLATTENING"','THE METAVERSE: WROTE OFF']},
 stamps:{
  hot:['$2T','ATH','3.4B','LEGS','∞'],
  mid:['520','P/E 24','52W','?','568'],
  cold:['−35%','▼','−$20B','EMPTY','520']},
 quotes:{
  hot:['“the metaverse is the next chapter”','“move fast and break things”','“we’re building the future”',
   '“i think we should be optimistic”'],
  mid:['“senator, we run ads”','“it’s a marathon, not a sprint”','“this is the year of efficiency”'],
  cold:['“we remain committed to reality labs”','“the legs are coming”','“temporary headwinds”',
   '“no one could have predicted users wouldn’t come”']},
 pageidx:{
  hot:'MARKETS B1 · TECH C3 · OPINION A19 · YACHTS D4',
  mid:'MARKETS B1 · TECH C3 · PRIVACY C9 · OBITUARIES D7',
  cold:'MARKETS B1 · LAYOFFS C1 · PRIVACY C9 · OBITUARIES D7'},
 corpus:{
  hot:'He renamed the company after the thing he was sure came next, and the market clapped. Billions flow into '
   +'headsets nobody wears and avatars nobody asked for, and the ad machine in the basement pays for all of it, '
   +'relentless, frictionless, infinite. Move fast, the wall used to say. Now it says superintelligence. The toll '
   +'on attention is collected in milliseconds, three billion times a day.',
  mid:'Somewhere under the pivots there is still the most efficient attention-harvesting machine ever built, warm '
   +'and quiet and enormous. The founder testifies, apologizes, rebrands, and ships. Whether the metaverse is the '
   +'future of human connection or a very expensive screensaver depends on who you ask and which keynote you watched.',
  cold:'Reality Labs loses another billion into a world with no weather and no people. The legs arrived a year late '
   +'and walked into an empty room. The same machine that prints money on ads now writes off the future it promised. '
   +'Move fast, the wall said; gravity, it turns out, moves faster.'},
 sect:[['GOOG',180],['SNAP',9],['PINS',32],['RDDT',120],['NVDA',120],['APP',310]],
 earn:[['REV',42,4,'B'],['ADS',40,4,'B'],['RL LOSS',-4.5,1,'B'],['OP MARGIN',42,4,'%'],['EPS',23.1,2,''],['CAPEX',65,8,'B']]},
cz:{
 name:'Changpeng Zhao',ticker:'BNB',low:380,high:760,ath:'760',copy:'FUNDS ARE SAFU',
 bubbleRow:['THE EXCHANGE','20__','2022'],
 heads:{hot:['BINANCE RUNS THE WORLD','BNB TO THE MOON','THE EXCHANGE THAT ATE CRYPTO','SAFU FOREVER',
   'BUILD WHILE THEY FUD','FOUR. (THAT IS THE TWEET)','VOLUME IS DESTINY','THE LARGEST CASINO ON EARTH'],
  mid:['IS BINANCE TOO BIG?','WHERE ARE THE RESERVES?','REGULATORS CIRCLE','SETTLE AND BUILD',
   'WHO AUDITS THE AUDITOR?','COMPLIANCE OR GROWTH?','THE $4.3 BILLION QUESTION'],
  cold:['THE PLEA DEAL','OUTFLOWS DEEPEN','SAFU, UNTIL IT IS NOT','THE FOUNDER STEPS DOWN',
   'PROOF OF RESERVES, PLEASE','THE WALLED GARDEN CRACKS','VOLUME EVAPORATES']},
 ticks:{hot:['BNB 760 ▲ ATH · VOL #1','BINANCE 24H $42B · USERS 250M','SAFU FUND $1B · BURN Q ▲',
   'BNB CHAIN TPS 2,100 · GAS LOW'],
  mid:['BNB · 52W 380–760','BNB 540 · MKT CAP $80B','SETTLEMENT $4.3B · MONITOR ON','RESERVES "1:1"'],
  cold:['BNB 380 ▼ −50% OFF HIGH','OUTFLOWS $6B/WK · TRUST ▼','VOLUME ▼ · RIVALS ▲','SAFU FUND DRAWN DOWN']},
 stamps:{hot:['ATH','#1','SAFU','4','+90%'],mid:['540','52W','$80B','?'],cold:['−50%','▼','PLEA','380','SAFU?']},
 quotes:{hot:['“funds are safu”','“4.”','“ignore FUD, keep building”','“we are the people’s exchange”'],
  mid:['“we welcome regulation”','“reserves are one to one”','“tigers don’t lose sleep over the opinions of sheep”'],
  cold:['“i made mistakes and i must take responsibility”','“the fundamentals are strong”','“we are cooperating fully”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · OPINION A19 · LUXURY D4',mid:'MARKETS B1 · CRYPTO C1 · REGULATION C9 · OBITUARIES D7',
  cold:'MARKETS B1 · ENFORCEMENT C1 · OUTFLOWS D2 · OBITUARIES D7'},
 corpus:{hot:'The largest casino on earth never closes and never sleeps, and the house token rises with every spin. Build while they doubt, the founder says, and four is a complete sentence.',
  mid:'Somewhere between the order book and the indictment there is a global exchange, vast and opaque, settling billions while the monitors take notes. Reserves are one to one, the dashboard says, and the dashboard is also the exchange.',
  cold:'Funds are safu until the morning the outflows say otherwise. The founder takes responsibility, the fund draws down, and the volume that was the whole thesis leaves for a quieter venue.'},
 sect:[['BTC',74300],['ETH',1670],['SOL',88],['XRP',2.1],['OKB',48],['BGB',1.2]],
 earn:[['24H VOL',42,8,'B'],['USERS',250,20,'M'],['SAFU',1,0.2,'B'],['BNB BURN',1.1,0.3,'B'],['MKT CAP',80,15,'B']]},
trump:{
 name:'Donald Trump',ticker:'TRUMP',low:3.5,high:75.0,ath:'75.00',copy:'THE ART OF THE DEAL',
 bubbleRow:['THE MEME PRESIDENCY','20__','2025'],
 heads:{hot:['EVERYTHING IS A DEAL','THE MEMECOIN PRESIDENCY','TREMENDOUS, THE BEST COIN','BUY TRUMP, BE HAPPY',
   'NOBODY DOES BUBBLES BIGGER','WE ARE GOING TO WIN SO MUCH','THE GREATEST COIN IN HISTORY'],
  mid:['IS THIS LEGAL?','WHO IS BUYING?','THE DINNER COSTS HOW MUCH?','GRIFT OR GENIUS?',
   'THE CONFLICT OF INTEREST','A COIN OR A CAMPAIGN?'],
  cold:['THE BAGHOLDERS','DOWN 90% FROM LAUNCH','THE INSIDERS CASHED OUT','SAD!',
   'THE DINNER IS OVER','WHO HOLDS THE BAG NOW?','THE DEAL THAT WASN’T']},
 ticks:{hot:['TRUMP 75.00 ▲ LAUNCH DAY · MCAP $14B','VOL $30B · HOLDERS 600K','TOP 40 WALLETS 80% SUPPLY'],
  mid:['TRUMP · 52W 3.50–75.00','TRUMP 9.00 · UNLOCKS PENDING','INSIDERS 80% · FLOAT THIN'],
  cold:['TRUMP 3.50 ▼ −95% FROM LAUNCH','HOLDERS UNDERWATER 82%','VOLUME ▼ · DINNER CANCELLED','LIQUIDITY GONE']},
 stamps:{hot:['ATH','75','HUGE','$14B','WIN'],mid:['9.00','52W','?','THIN'],cold:['−95%','▼','SAD!','3.50','BAGS']},
 quotes:{hot:['“it’s going to be tremendous, believe me”','“nobody does deals like me”','“buy my coin, it’s beautiful”'],
  mid:['“many people are saying”','“we’ll see what happens”','“it’s a very fair deal”'],
  cold:['“i don’t know anything about it”','“that was a long time ago”','“the fake news media”','“sad!”']},
 pageidx:{hot:'MARKETS B1 · POLITICS A1 · OPINION A19 · GOLF D4',mid:'MARKETS B1 · POLITICS A1 · ETHICS C9 · OBITUARIES D7',
  cold:'MARKETS B1 · LITIGATION C1 · BAGHOLDERS D2 · OBITUARIES D7'},
 corpus:{hot:'The deal was the coin and the coin was the deal, launched at midnight to a roar of believers. Tremendous, the best, the biggest bubble anyone has ever seen, and the dinner sold out in minutes.',
  mid:'Somewhere between the rally and the unlock schedule there is a token with a famous face and a thin float, eighty percent held by people who are not you. Many people are saying it is a very fair deal.',
  cold:'The insiders cashed out at the top, as insiders do, and the bagholders held the only thing left: the merchandise. Down ninety-five percent, the founder knows nothing about it, and the media is fake.'},
 sect:[['BTC',74300],['DOGE',0.17],['MELANIA',0.9],['PEPE',0.000008],['WLFI',0.2],['DJT',22]],
 earn:[['MCAP',14,3,'B'],['HOLDERS',600,80,'K'],['INSIDER %',80,5,'%'],['VOL',30,8,'B'],['FLOAT',20,3,'%']]},
musk:{
 name:'Elon Musk',ticker:'DOGE',low:0.07,high:0.48,ath:'0.48',copy:'MUCH WOW',
 bubbleRow:['THE MEME ECONOMY','20__','2021'],
 heads:{hot:['DOGE TO THE MOON','THE PEOPLE’S CRYPTO','ONE TWEET, ONE RALLY','MARS NEEDS DOGECOIN',
   'FUNDING SECURED','MUCH WOW. SO BUBBLE.','THE RICHEST MAN TWEETS AGAIN','X PAYMENTS INCOMING'],
  mid:['IS IT A JOKE OR NOT?','THE TWEET MOVED THE MARKET','SEC OR MEME?','420, AGAIN?',
   'WHO IS DRIVING TESLA?','PROMISE OR PUMP?'],
  cold:['THE TWEETS GO QUIET','DOWN FROM THE MOON','THE JOKE STOPPED BEING FUNNY','AUTOPILOT OFF',
   'NO ROBOTAXI, AGAIN','THE MEME PREMIUM EVAPORATES','SO EMPTY. MUCH CRASH.']},
 ticks:{hot:['DOGE 0.48 ▲ ATH · ONE TWEET','TSLA P/E 110 · MEME PREMIUM ▲','X PAYMENTS "SOON" · DAU ▲'],
  mid:['DOGE · 52W 0.07–0.48','DOGE 0.17 · TWEET PENDING','TSLA DELIVERIES FLAT · P/E 60'],
  cold:['DOGE 0.07 ▼ −85% OFF HIGH','TWEET SILENCE · VOL ▼','TSLA −40% · ROBOTAXI DELAYED','MEME PREMIUM GONE']},
 stamps:{hot:['ATH','420','WOW','69','MOON'],mid:['0.17','52W','?','MEME'],cold:['−85%','▼','0.07','EMPTY','SAD']},
 quotes:{hot:['“doge to the moon”','“funding secured”','“much wow”','“the most entertaining outcome is the most likely”'],
  mid:['“probably nothing”','“we’ll see”','“i am become meme, destroyer of shorts”'],
  cold:['“deleting my tweet”','“that was taken out of context”','“tesla is not a car company”','“so it goes”']},
 pageidx:{hot:'MARKETS B1 · TECH C3 · OPINION A19 · SPACE D4',mid:'MARKETS B1 · TECH C3 · SEC FILINGS C9 · OBITUARIES D7',
  cold:'MARKETS B1 · RECALLS C1 · LAWSUITS D2 · OBITUARIES D7'},
 corpus:{hot:'A single tweet at three in the morning and the people’s crypto goes vertical. Much wow, so bubble, funding secured at four-twenty, and the most entertaining outcome remains the most likely.',
  mid:'Somewhere between the rocket and the recall there is a joke that became a currency and a currency that became a religion. Probably nothing, the founder posts, and the market reads scripture into it.',
  cold:'The tweets go quiet and the moon turns out to be a screen. Down eighty-five percent, the robotaxi is always next year, and the meme premium leaves the way memes do — all at once, to nowhere.'},
 sect:[['BTC',74300],['SHIB',0.000018],['TSLA',230],['PEPE',0.000008],['FLOKI',0.0001],['BONK',0.00002]],
 earn:[['DOGE',0.17,0.1,''],['TSLA',230,40,''],['X DAU',250,30,'M'],['DELIVERIES',1.8,0.3,'M'],['P/E',60,20,'']]},
sbf:{
 name:'Sam Bankman-Fried',ticker:'FTT',low:0.9,high:55.0,ath:'55.00',copy:'EFFECTIVE ALTRUISM',
 bubbleRow:['THE CRYPTO EXCHANGE','20__','2022'],
 heads:{hot:['FTX SAVES CRYPTO','THE MOST GENEROUS BILLIONAIRE','EFFECTIVE ALTRUISM PAYS','THE WHITE KNIGHT OF CRYPTO',
   'SLEEP IS FOR THE WEAK','BUY THE NAMING RIGHTS','THE GENIUS IN CARGO SHORTS'],
  mid:['WHERE ARE THE FUNDS?','ALAMEDA AND FTX, AGAIN?','A LIQUIDITY ISSUE?','THE BALANCE SHEET QUESTION',
   'GENEROUS OR LEVERAGED?','WHO AUDITS FTX?'],
  cold:['THE COLLAPSE','$8 BILLION MISSING','THE WHITE KNIGHT IS A FRAUD','GUILTY ON ALL COUNTS',
   'IT WAS NEVER REAL','THE ALTRUISM WAS A COSTUME','25 YEARS']},
 ticks:{hot:['FTT 55.00 ▲ ATH · FTX #2','VALUATION $32B · VCs ALL IN','NAMING RIGHTS $135M · A-LIST'],
  mid:['FTT · 52W 0.90–55.00','FTT 22 · WITHDRAWALS SLOW','ALAMEDA B/S 40% FTT'],
  cold:['FTT 0.90 ▼ −98% · HALTED','WITHDRAWALS FROZEN · $8B GAP','BANKRUPTCY CH.11 · FRAUD','EQUITY: ZERO']},
 stamps:{hot:['ATH','$32B','EA','55','GENIUS'],mid:['22','52W','?','SLOW'],cold:['−98%','▼','FRAUD','0.90','GONE']},
 quotes:{hot:['“i’m giving it all away”','“sleep is overrated”','“we have plenty of liquidity”','“ftx is fine. assets are fine.”'],
  mid:['“it’s a complicated situation”','“i was as surprised as anyone”','“ethics is a dumb question”'],
  cold:['“i never meant to defraud anyone”','“i made a lot of mistakes”','“um”','“i f----d up”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · PHILANTHROPY D4 · SPORTS C6',mid:'MARKETS B1 · CRYPTO C1 · REGULATION C9 · OBITUARIES D7',
  cold:'MARKETS B1 · COURTS A1 · BANKRUPTCY D2 · OBITUARIES D7'},
 corpus:{hot:'The most generous man in crypto slept on a beanbag and gave it all away, or said he would. Effective altruism scaled to nine figures, naming rights on the arena, and the venture capital queued at the door.',
  mid:'Somewhere between Alameda and FTX there was supposed to be a wall, and there was not. Plenty of liquidity, the founder typed, and the withdrawals slowed to a trickle while the token that backed it backed nothing.',
  cold:'Eight billion dollars went somewhere and the somewhere was a customer ledger used as a piggy bank. The altruism was a costume, the genius was leverage, and the verdict was guilty on all counts.'},
 sect:[['BTC',74300],['SOL',88],['SRM',0.02],['COIN',210],['BNB',540],['GBTC',60]],
 earn:[['CUST GAP',8,1,'B'],['VALUATION',0,0,''],['FTT',0.9,0.5,''],['SENTENCE',25,0,'YR'],['RECOVERY',30,10,'%']]},
cathie:{
 name:'Cathie Wood',ticker:'ARKK',low:38,high:88,ath:'88.00',copy:'DISRUPTIVE INNOVATION',
 bubbleRow:['DISRUPTIVE INNOVATION','20__','2021'],
 heads:{hot:['INNOVATION EATS THE WORLD','5X IN FIVE YEARS','THE FUTURE IS DEFLATIONARY','BUY THE INNOVATION DIP',
   'WE ARE STILL EARLY','GENOMICS, AI, CRYPTO, REPEAT','CONVICTION PAYS'],
  mid:['IS THE THESIS BROKEN?','WHEN DOES EARLY END?','HIGH CONVICTION, HIGH BETA','THE FLOWS REVERSE',
   'DEFLATION OR DRAWDOWN?','PRICE TARGETS, REVISED UP'],
  cold:['THE INNOVATION WINTER','DOWN 70% FROM HIGH','CONVICTION MEETS REDEMPTIONS','BUYING THE LOSERS',
   'STILL EARLY, STILL LOWER','THE FIVE-YEAR PLAN SLIPS','FLOWS EXIT THE FUTURE']},
 ticks:{hot:['ARKK 88.00 ▲ · AUM $28B','BUYS THE DIP DAILY · CONVICTION ▲','TSLA TARGET $2,000 · BTC $1.5M'],
  mid:['ARKK · 52W 38–88','ARKK 52 · OUTFLOWS START','TOP HOLDINGS HIGH BETA'],
  cold:['ARKK 38 ▼ −57% OFF HIGH','OUTFLOWS 11 WEEKS · AUM ▼','STILL EARLY, FUND SAYS','REDEMPTIONS ▲']},
 stamps:{hot:['5X','ATH','$28B','EARLY','+100%'],mid:['52','52W','?','BETA'],cold:['−57%','▼','38','WINTER','EARLY?']},
 quotes:{hot:['“we believe innovation is the key to growth”','“five-fold in five years”','“we are in a deflationary boom”','“buy the dip”'],
  mid:['“our conviction is higher than ever”','“the market is wrong, not us”','“time arbitrage”'],
  cold:['“we are still in the early innings”','“our five-year horizon is intact”','“volatility is opportunity”']},
 pageidx:{hot:'MARKETS B1 · TECH C3 · OPINION A19 · FUTURES D4',mid:'MARKETS B1 · FUNDS C3 · FLOWS C9 · OBITUARIES D7',
  cold:'MARKETS B1 · REDEMPTIONS C1 · INNOVATION D2 · OBITUARIES D7'},
 corpus:{hot:'The future is deflationary and the fund is its prophet, five-fold in five years, conviction compounding faster than revenue. Buy the dip, the thesis says, and the dip is just the future on sale.',
  mid:'Somewhere between the price target and the redemption notice there is a portfolio of pure tomorrow, high conviction and higher beta. We are still early, the letter says, and early is a place that keeps receding.',
  cold:'Innovation has a winter and the flows have a memory. Down seventy percent, still buying the losers with other people’s patience, still early — a phrase that ages like the chart it describes.'},
 sect:[['TSLA',230],['COIN',210],['ROKU',55],['PATH',12],['HOOD',98],['RBLX',38]],
 earn:[['AUM',28,5,'B'],['ARKK',52,10,''],['FLOWS',-1.2,0.5,'B'],['TOP10 %',62,5,'%'],['BETA',1.6,0.3,'']]},
buffett:{
 name:'Warren Buffett',ticker:'BRK',low:408,high:558,ath:'558.00',copy:'CASH IS A POSITION',
 bubbleRow:['EVERY BUBBLE SINCE 1956','—','—'],
 heads:{hot:['THE ORACLE STAYS PATIENT','RECORD CASH PILE','NEVER BET AGAINST AMERICA','BUY WONDERFUL COMPANIES',
   'THE COMPOUNDING MACHINE','BOREDOM IS A STRATEGY','A FORTRESS OF FLOAT'],
  mid:['WHY IS HE HOLDING CASH?','IS HE TOO CAUTIOUS?','THE SUCCESSION QUESTION','TOO BIG TO BEAT THE INDEX?',
   'WHEN DOES HE BUY?','THE $300 BILLION QUESTION'],
  cold:['BE GREEDY NOW?','THE TIDE GOES OUT','WHO IS SWIMMING NAKED?','THE PATIENT MAN GOES SHOPPING',
   'CASH BECOMES KING','THE ORACLE WAS RIGHT, AGAIN','BLOOD IN THE STREETS, BUY']},
 ticks:{hot:['BRK.B 558 ▲ ATH · CASH $300B','FLOAT $170B · NO DIVIDEND','BUYBACKS PAUSED · TOO EXPENSIVE'],
  mid:['BRK.B · 52W 408–558','BRK.B 500 · CASH RECORD','S&P BEAT: NARROW'],
  cold:['BRK.B 408 ▼ · ORACLE BUYS','CASH DEPLOYED $50B · BARGAINS','FEAR INDEX ▲ · HE SMILES','VALUE RETURNS']},
 stamps:{hot:['ATH','$300B','CASH','558','PATIENT'],mid:['500','52W','?','FLOAT'],cold:['BUY','▼','408','GREEDY','VALUE']},
 quotes:{hot:['“be fearful when others are greedy”','“our favorite holding period is forever”','“price is what you pay, value is what you get”','“never bet against america”'],
  mid:['“the stock market is a device for transferring money from the impatient to the patient”','“cash is a position”','“we don’t have to be smarter, just more disciplined”'],
  cold:['“be greedy when others are fearful”','“only when the tide goes out do you see who was swimming naked”','“the best chance to deploy capital is when things are going down”']},
 pageidx:{hot:'MARKETS B1 · VALUE C3 · OPINION A19 · CANDY D4',mid:'MARKETS B1 · VALUE C3 · SUCCESSION C9 · OBITUARIES D7',
  cold:'MARKETS B1 · BARGAINS C1 · VALUE D2 · OBITUARIES D7'},
 corpus:{hot:'While the world chases the new thing, the oracle sits on a mountain of cash and a river of float, patient to the point of boredom. Be fearful when others are greedy, he says, and the cash pile is the fear made visible.',
  mid:'Somewhere between the annual letter and the candy company there is a compounding machine that has outlived every bubble it declined to join. The favorite holding period is forever, which is also how long the cash has waited.',
  cold:'When the tide goes out the patient man goes shopping. Three hundred billion in dry powder meets blood in the streets, and the oracle, who was right about every mania he sat out, finally swings.'},
 sect:[['AAPL',230],['KO',62],['BAC',38],['AXP',280],['OXY',55],['SPY',680]],
 earn:[['CASH',300,30,'B'],['FLOAT',170,15,'B'],['BRK.B',500,40,''],['OP EARN',40,5,'B'],['BUYBACK',0,2,'B']]},
armstrong:{
 name:'Brian Armstrong',ticker:'COIN',low:140,high:360,ath:'360.00',copy:'WE ARE COOPERATING',
 bubbleRow:['THE EXCHANGE','20__','2021'],
 heads:{hot:['COINBASE GOES MAINSTREAM','THE ONRAMP TO CRYPTO','REGULATION BY ENFORCEMENT, WE WIN','BASE EATS ETHEREUM',
   'A MILLION DEVELOPERS','THE COMPLIANT CASINO','LISTING IS DESTINY'],
  mid:['SECURITY OR COMMODITY?','THE SEC LAWSUIT, AGAIN','TRADING REV OR SUBSCRIPTION?','HOW MANY USERS REALLY?',
   'THE WELLS NOTICE','FEES OR FUTURE?'],
  cold:['VOLUME EVAPORATES','THE COMPLIANT EXCHANGE, EMPTY','LAYOFFS AT THE ONRAMP','FEES COMPRESS',
   'THE LAWSUIT DRAGS ON','NO ONE IS TRADING','THE CASINO CLOSED EARLY']},
 ticks:{hot:['COIN 360 ▲ · VOL #1 US','MTU 12M · ASSETS $400B','BASE TVL $8B · FEES ▲'],
  mid:['COIN · 52W 140–360','COIN 210 · SEC PENDING','TRADING REV 60% · CYCLICAL'],
  cold:['COIN 140 ▼ −61% OFF HIGH','VOLUME ▼ 70% · FEES ▼','LAYOFFS 18% · COST CUTS','MTU 6M ▼']},
 stamps:{hot:['ATH','#1','BASE','360','+80%'],mid:['210','52W','?','SEC'],cold:['−61%','▼','140','EMPTY','SUED']},
 quotes:{hot:['“we are the most trusted name in crypto”','“economic freedom for everyone”','“base is for builders”','“regulation will be good for us”'],
  mid:['“we welcome clear rules”','“we are cooperating with the sec”','“crypto is going mainstream”'],
  cold:['“we will see them in court”','“this is a temporary slowdown”','“we remain well capitalized”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · OPINION A19 · TECH D4',mid:'MARKETS B1 · CRYPTO C1 · LITIGATION C9 · OBITUARIES D7',
  cold:'MARKETS B1 · ENFORCEMENT C1 · LAYOFFS D2 · OBITUARIES D7'},
 corpus:{hot:'The compliant casino has the cleanest floor in town and the regulators on speed dial. Economic freedom for everyone, the mission says, settled in dollars, listed on the Nasdaq, audited and onramped.',
  mid:'Somewhere between the Wells notice and the quarterly call there is an exchange whose revenue rises and falls with a mania it cannot control. We are cooperating, the filing says, and the lawyers bill by the hour.',
  cold:'When the volume leaves, the compliant exchange is just an expensive lobby with very good lighting. Fees compress, the lawsuit drags, and the most trusted name in crypto cuts eighteen percent of the people who built it.'},
 sect:[['BTC',74300],['ETH',1670],['HOOD',98],['MSTR',120],['SQ',62],['PYPL',58]],
 earn:[['MTU',12,2,'M'],['ASSETS',400,50,'B'],['TRADING %',60,8,'%'],['COIN',210,40,''],['BASE TVL',8,3,'B']]},
dorsey:{
 name:'Jack Dorsey',ticker:'BTC',low:58000,high:112000,ath:'112,000',copy:'BITCOIN FIXES THIS',
 bubbleRow:['DIGITAL GOLD','20__','—'],
 heads:{hot:['BITCOIN IS THE NATIVE CURRENCY','HYPERBITCOINIZATION','THE ORANGE FUTURE','BITCOIN FIXES THIS',
   'STACK SATS, STAY HUMBLE','NUMBER GO UP','THE PEOPLE’S MONEY WINS'],
  mid:['STORE OF VALUE OR BUBBLE?','WHERE IS THE UTILITY?','THE VOLATILITY QUESTION','MAXI OR REALIST?',
   'CUSTODY OR CONTROL?','DIGITAL GOLD, DISCOUNTED'],
  cold:['THE WINTER RETURNS','DOWN FROM SIX FIGURES','HODL MEETS MARGIN CALL','THE FAITHFUL CAPITULATE',
   'MINERS GO DARK','THE ORANGE FUTURE, DEFERRED','STILL EARLY, STILL BLEEDING']},
 ticks:{hot:['BTC 112,000 ▲ ATH · HALVING DONE','HASHRATE ATH · FEES ▲','ETF INFLOWS $2B/WK · MSTR BUYS'],
  mid:['BTC · 52W 58,000–112,000','BTC 74,300 · CONSOLIDATING','DOMINANCE 58% · FEAR/GREED 50'],
  cold:['BTC 58,000 ▼ −48% OFF HIGH','ETF OUTFLOWS · MINERS ▼','HASHRATE −20% · CAPITULATION','LONG-TERM HOLDERS SELL']},
 stamps:{hot:['ATH','21M','₿','112K','STACK'],mid:['74K','52W','?','HODL'],cold:['−48%','▼','58K','WINTER','CAPITULATE']},
 quotes:{hot:['“bitcoin will be the native currency of the internet”','“stack sats, stay humble”','“fix the money, fix the world”','“not your keys, not your coins”'],
  mid:['“bitcoin is resilient”','“i only own bitcoin”','“the protocol does not care about price”'],
  cold:['“zoom out”','“we are still early”','“the fundamentals have never been stronger”','“have fun staying poor”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · OPINION A19 · TECH D4',mid:'MARKETS B1 · CRYPTO C1 · MINING C9 · OBITUARIES D7',
  cold:'MARKETS B1 · LIQUIDATIONS C1 · MINING D2 · OBITUARIES D7'},
 corpus:{hot:'Fix the money and you fix the world, the founder says, stacking sats with the patience of a monk and the certainty of a prophet. Hyperbitcoinization is not if but when, and the orange future arrives one block at a time.',
  mid:'Somewhere between the white paper and the price chart there is a protocol that does not care what you paid. Bitcoin is resilient, the maxi says, and resilience is what you call volatility you have decided to love.',
  cold:'The winter returns on schedule, indifferent as the protocol itself. Down forty-eight percent, the faithful zoom out, the miners go dark, and still early becomes the longest sentence in the language.'},
 sect:[['ETH',1670],['SOL',88],['MSTR',120],['COIN',210],['MARA',17],['GLD',310]],
 earn:[['BTC',74300,0,''],['HASHRATE',620,40,'EH'],['DOMINANCE',58,4,'%'],['ETF AUM',95,15,'B'],['SUPPLY',19.8,0.1,'M']]},
dimon:{
 name:'Jamie Dimon',ticker:'JPM',low:200,high:320,ath:'320.00',copy:'A FORTRESS BALANCE SHEET',
 bubbleRow:['EVERY CRYPTO BUBBLE','—','—'],
 heads:{hot:['THE FORTRESS NEVER FALLS','RECORD PROFITS, AGAIN','THE LAST BANKER STANDING','TOO STRONG TO FAIL',
   'A FORTRESS BALANCE SHEET','DEPOSITS FLEE TO QUALITY','THE BANK THAT EATS BANKS'],
  mid:['IS CRYPTO A FRAUD?','THE STORM CLOUDS GATHER','WHEN DOES THE CYCLE TURN?','RATES OR RECESSION?',
   'THE SUCCESSION QUESTION','PET ROCK OR PAYMENT RAIL?'],
  cold:['THE STORM ARRIVES','CREDIT LOSSES MOUNT','EVEN THE FORTRESS BLEEDS','THE CYCLE TURNS',
   'PROVISIONS BALLOON','THE BANKER WAS RIGHT TO WORRY','RECESSION, AS PROMISED']},
 ticks:{hot:['JPM 320 ▲ ATH · ROE 18%','NET INCOME $50B · FORTRESS','DEPOSITS ▲ · FLIGHT TO QUALITY'],
  mid:['JPM · 52W 200–320','JPM 272 · STORM CLOUDS','NIM PEAKS · CREDIT NORMALIZES'],
  cold:['JPM 200 ▼ −37% · PROVISIONS ▲','CREDIT LOSSES $8B/Q','RECESSION BASE CASE · RWA ▲','BUYBACKS PAUSED']},
 stamps:{hot:['ATH','$50B','ROE 18','320','FORTRESS'],mid:['272','52W','?','STORM'],cold:['−37%','▼','200','LOSSES','STORM']},
 quotes:{hot:['“we have a fortress balance sheet”','“america is the most prosperous nation on earth”','“we are prepared for anything”'],
  mid:['“there are storm clouds on the horizon”','“i could care less about bitcoin”','“crypto is a decentralized ponzi”'],
  cold:['“bitcoin is a pet rock”','“i told you so is not a strategy, but i did tell you”','“if i were the government i would close it down”','“this is the most dangerous time in decades”']},
 pageidx:{hot:'MARKETS B1 · BANKING C3 · OPINION A19 · WEALTH D4',mid:'MARKETS B1 · BANKING C3 · CREDIT C9 · OBITUARIES D7',
  cold:'MARKETS B1 · CREDIT C1 · DEFAULTS D2 · OBITUARIES D7'},
 corpus:{hot:'The fortress was built for weather that has not arrived yet, deposits fleeing to quality, profits stacking like sandbags. America is the most prosperous nation on earth, the banker says, and the bank is its largest landlord.',
  mid:'Somewhere between the earnings call and the warning there is a banker who calls every bubble a fraud and is right often enough to be insufferable. Storm clouds on the horizon, he repeats, until the horizon obliges.',
  cold:'The storm arrives as promised and even the fortress takes water. Credit losses mount, provisions balloon, and the man who called bitcoin a pet rock collects the grim satisfaction of having warned everyone who would not listen.'},
 sect:[['BAC',38],['WFC',62],['C',58],['GS',480],['MS',105],['XLF',45]],
 earn:[['NET INC',50,5,'B'],['ROE',18,2,'%'],['DEPOSITS',2400,100,'B'],['JPM',272,30,''],['PROVISIONS',3,2,'B']]},
dokwon:{
 name:'Do Kwon',ticker:'LUNA',low:0.0001,high:119.18,ath:'119.18',copy:'DEPLOYING MORE CAPITAL',
 bubbleRow:['THE ALGORITHMIC STABLECOIN','20__','2022'],
 heads:{hot:['LUNA TO 1000','THE STABLECOIN THAT CANNOT BREAK','DEPLOYING MORE CAPITAL','STEADY LADS',
   'THE DEATH SPIRAL IS A MYTH','UST IS THE FUTURE OF MONEY','MY CHILD IS NAMED LUNA'],
  mid:['CAN THE PEG HOLD?','WHAT BACKS THE STABLECOIN?','THE 20% YIELD QUESTION','ALGORITHMIC OR PONZI?',
   'WHERE IS THE BITCOIN RESERVE?','STEADY, OR SLIPPING?'],
  cold:['THE DEATH SPIRAL','FORTY BILLION GONE IN DAYS','THE PEG IS BROKEN','99% OF YOU WILL DIE',
   'THE STABLECOIN, UNSTABLE','THE FUGITIVE','ZERO. FINALIZED.']},
 ticks:{hot:['LUNA 119.18 ▲ ATH · UST $1.00','ANCHOR YIELD 20% · TVL $20B','BTC RESERVE $3B · LFG ▲'],
  mid:['LUNA · 52W 0.0001–119.18','LUNA 0.0001 · PEG WATCH','UST 0.98 · SLIPPING'],
  cold:['LUNA 0.0001 ▼ −99.99% · DEAD','UST 0.02 · PEG GONE','SUPPLY 6.9T · HYPERINFLATED','TVL: ZERO']},
 stamps:{hot:['ATH','1000','20%','119','STEADY'],mid:['PEG','52W','?','0.98'],cold:['−99.99%','▼','0','DEAD','SPIRAL']},
 quotes:{hot:['“deploying more capital — steady lads”','“by my hand $ust will flip $dai”','“ust is the future of decentralized money”'],
  mid:['“the peg is fine”','“i find it amusing that you doubt me”','“steady lads”'],
  cold:['“i am heartbroken”','“i never imagined this could happen”','“99% will die, but the 1% who survive...”','“i have nothing to hide”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · STABLECOINS D4',mid:'MARKETS B1 · CRYPTO C1 · STABLECOINS C9 · OBITUARIES D7',
  cold:'MARKETS B1 · COLLAPSE A1 · WARRANTS D2 · OBITUARIES D7'},
 corpus:{hot:'Twenty percent yield, forever, on a dollar that prints itself, backed by a coin that backs the dollar that backs the coin. Steady lads, the founder says, deploying more capital into a machine that only runs uphill.',
  mid:'Somewhere between the peg and the prayer there is a reflexive loop that holds beautifully until the moment it does not. The peg is fine, the founder posts, amused at the doubters who can read a death spiral coming.',
  cold:'Forty billion dollars evaporated in seventy-two hours and the stablecoin found its true value: nothing. The death spiral that could not happen happened, the founder fled, and ninety-nine percent did, in fact, die.'},
 sect:[['BTC',74300],['UST',0.02],['MIM',0.6],['FRAX',0.99],['USDC',1.0],['DAI',1.0]],
 earn:[['LUNA',0.0001,0,''],['UST PEG',0.02,0.05,''],['TVL',0,0,'B'],['SUPPLY',6900,100,'B'],['RECOVERY',0,1,'%']]},
sun:{
 name:'Justin Sun',ticker:'TRX',low:0.09,high:0.45,ath:'0.45',copy:'GUARANTEED YIELD',
 bubbleRow:['THE TRON','20__','—'],
 heads:{hot:['TRON EATS STABLECOINS','GUARANTEED YIELD, FOREVER','THE PEOPLE’S BLOCKCHAIN','BUY THE DIP, WIN THE LUNCH',
   'NUMBER GO UP, ALWAYS','THE MOST USED CHAIN','DECENTRALIZE EVERYTHING (LATER)'],
  mid:['IS THE YIELD REAL?','WHO RUNS THE NODES?','MARKETING OR PROTOCOL?','THE SEC, AGAIN?',
   'STABLECOIN HUB OR HOUSE OF CARDS?','GUARANTEED BY WHOM?'],
  cold:['THE YIELD WAS NOT GUARANTEED','OUTFLOWS HIT TRON','THE MARKETING STOPS','THE NODES GO QUIET',
   'THE PEG WOBBLES','REDEMPTIONS PAUSED','THE HUSTLE ENDS']},
 ticks:{hot:['TRX 0.45 ▲ ATH · USDT ON TRON $60B','STAKING APY 12% · "SAFE"','DAU 2M · FEES LOW'],
  mid:['TRX · 52W 0.09–0.45','TRX 0.27 · YIELD WATCH','USDT DOMINANCE ▲ · SEC PENDING'],
  cold:['TRX 0.09 ▼ −80% OFF HIGH','YIELD CUT · OUTFLOWS ▲','REDEMPTIONS SLOW · TRUST ▼','VOLUME EVAPORATES']},
 stamps:{hot:['ATH','12%','SAFE','0.45','YIELD'],mid:['0.27','52W','?','APY'],cold:['−80%','▼','0.09','PAUSED','HUSTLE']},
 quotes:{hot:['“guaranteed yield for all”','“tron is the most decentralized”','“buy the dip, i bought lunch”','“nothing can stop tron”'],
  mid:['“the yield is sustainable”','“we are fully compliant”','“decentralization is coming soon”'],
  cold:['“i never said guaranteed”','“this is fud”','“funds are safe, i assure you”','“i am traveling, no comment”']},
 pageidx:{hot:'MARKETS B1 · CRYPTO C1 · YIELD D4',mid:'MARKETS B1 · CRYPTO C1 · REGULATION C9 · OBITUARIES D7',
  cold:'MARKETS B1 · OUTFLOWS C1 · YIELD D2 · OBITUARIES D7'},
 corpus:{hot:'Guaranteed yield for everyone, forever, on the most used chain that no one can quite name a use for. Buy the dip, the founder says, and the dip comes with a free lunch and a photo opportunity.',
  mid:'Somewhere between the press release and the protocol there is a blockchain that is mostly a stablecoin pipe with a marketing budget. The yield is sustainable, the founder assures, and sustainability is a word that does a lot of work here.',
  cold:'The guaranteed yield discovers its asterisk and the outflows discover the door. The marketing stops, the nodes go quiet, and the founder is suddenly traveling, with no comment, somewhere with no extradition treaty.'},
 sect:[['BTC',74300],['ETH',1670],['USDT',1.0],['BNB',540],['XRP',2.1],['HT',1.4]],
 earn:[['TRX',0.27,0.1,''],['USDT ON TRX',60,10,'B'],['DAU',2,0.5,'M'],['APY',12,3,'%'],['TVL',9,3,'B']]},
ternus:{
 name:'John Ternus',ticker:'AAPL',low:198,high:288,ath:'288.00',copy:'THE NEW HANDS',
 bubbleRow:['THE BIGGEST COMPANY','20__','2000'],
 heads:{hot:['THE ENGINEER TAKES THE THRONE','APPLE HITS $4 TRILLION','A SMOOTH SUCCESSION','SERVICES EAT THE WORLD',
   'THE QUIET GIANT, NEW HANDS','A BILLION PAYING USERS','SHIP IT, THEN SHIP IT AGAIN'],
  mid:['CAN HE FILL THE SHOES?','WHERE IS THE GROWTH?','IS AI TOO LATE?','THE CHINA QUESTION',
   'ENGINEER OR OPERATOR?','THE FIRST KEYNOTE TEST'],
  cold:['THE NEW GUY INHERITS A STALL','IPHONE SALES DECLINE','THE LOST DECADE, MAYBE','CHINA REVENUE SLIPS',
   'ANTITRUST BITES','THE MAGIC FADES','BIG SHOES, COLD FEET']},
 ticks:{hot:['AAPL 288 ▲ ATH · MKT CAP $4.2T','SERVICES +14% · MARGIN 70%','BUYBACK $90B · CASH $60B'],
  mid:['AAPL · 52W 198–288','AAPL 232 · CHINA WATCH','IPHONE FLAT · SERVICES ▲'],
  cold:['AAPL 198 ▼ −31% OFF HIGH','IPHONE −12% · CHINA −20%','SERVICES +4% · DECEL','ANTITRUST FINE $20B']},
 stamps:{hot:['$4T','ATH','+14%','288','GIANT'],mid:['232','52W','?','CHINA'],cold:['−31%','▼','198','PEAK','STALL']},
 quotes:{hot:['“the best products in the world”','“we sweat every detail”','“hardware and software, as one”','“our best quarter ever”'],
  mid:['“i wasn’t sure i belonged”','“big shoes to fill”','“we have a deep pipeline”'],
  cold:['“we faced some headwinds”','“we remain confident in the long term”','“the transition takes time”']},
 pageidx:{hot:'MARKETS B1 · TECH C3 · OPINION A19 · DESIGN D4',mid:'MARKETS B1 · TECH C3 · ANTITRUST C9 · OBITUARIES D7',
  cold:'MARKETS B1 · ANTITRUST C1 · SUPPLY CHAIN D2 · OBITUARIES D7'},
 corpus:{hot:'The engineer who built the pipeline now inherits the throne, a trillion-dollar machine handed over with a handshake and a keynote. The best products in the world, the new chief says quietly, and a billion people pay monthly to agree while the founder-operator watches from the chairman’s seat.',
  mid:'Somewhere between the soldering iron and the shareholder letter there is a hardware lifer learning to speak in guidance. Big shoes to fill, he admits, and the most valuable company on earth measures every word of its eighth chief executive.',
  cold:'The new hands inherit an old problem: even giants have a lost decade. iPhone sales decline, China slips, the magic that sold the story cools, and the engineer discovers that running the machine is harder than building it.'},
 sect:[['MSFT',410],['GOOG',180],['NVDA',120],['AMZN',190],['SAMSUNG',55],['XLK',240]],
 earn:[['REV',95,8,'B'],['SERVICES',26,3,'B'],['GM',46,3,'%'],['EPS',1.6,0.3,''],['BUYBACK',90,10,'B'],['CASH',60,10,'B']]}
};
